name: "Control de Cambios"
description: "STI-ST-916 • Solicitar y gestionar un cambio"
title: "CC: {sistema}/{modulo} - {titulo corto}"
labels: ["enhancement"]
type: "Feature"
projects: "github/6"
body:

  - type: dropdown
    id: sistema
    attributes:
      label: Sistema
      options: ["Smartsys","MyReporting","Novedades Online","AGLA","BDOapps","Anysign","Linea Etica","Validacion de compras","MyDocsWeb"]
    validations: { required: true }
    
  - type: dropdown
    id: tipo
    attributes:
      label: Tipo de cambio
      options: ["Funcional","Seguridad","Regional/Legal","Deuda tecnica"]
    validations: { required: true }

  - type: dropdown
    id: prioridad
    attributes:
      label: Prioridad
      options: ["Urgente", "Alta","Media","Baja"]
    validations: { required: true }    

  - type: input
    id: ticket
    attributes:
      label: ID Ticket
      placeholder: "#12345"
    validations:
      required: true

  - type: textarea
    id: descripcion
    attributes:
      label: Descripción general del cambio
      description: "Resume el objetivo del cambio y el problema que soluciona. Adjunta analisis de beneficio de ser el caso."
      value: |
        ## Plantilla sugerida (edita libremente)
        **Contexto**: _Describe el problema/solicitud y el impacto actual._
        **Objetivo del cambio**: _Qué se busca lograr y por qué._
        **Alcance**:
        - Sistemas/Módulos involucrados: (Usuarios/Empresas/Reportes)
        - Fuera de alcance:
        **Suposiciones**:
        - ...
        **Criterios de aceptacion**:
        - Formato Gherkin (Feature, Scenario, Given, When, Then)
    validations:
      required: true

  - type: textarea
    id: impacto
    attributes:
      label: Análisis de impacto
      description: "Elementos afectados, compatibilidad, seguridad y riesgos."
      value: |
        **Elementos afectados**: tablas, endpoints, jobs, UI, permisos.
        **Seguridad**: headers, TLS, XSS, dependencias.
        **Riesgos**: ...
        **Mitigaciones**: ...

  - type: textarea
    id: plan
    attributes:
      label: Plan de trabajo
      description: "Adjunta el Gantt del proyecto"

  - type: input
    id: autorizado_por
    attributes:
      label: Autorizado por
      placeholder: "PO del sistema/modulo"

  - type: input
    id: esfuerzo
    attributes:
      label: Esfuerzo estimado (horas)
      placeholder: "Ej.: 40.5"

  - type: input
    id: costo
    attributes:
      label: Costo asociado (S/ o USD)
      placeholder: "Ej.: S/ 1,593.17"

  - type: textarea
    id: arquitectura
    attributes:
      label: Documento de arquitectura o ADRs
      description: "Adjunta documentos elaborados"

  - type: textarea
    id: bd
    attributes:
      label: Documento de base de datos
      description: "Adjunta documentos elaborados"

  - type: textarea
    id: riesgos
    attributes:
      label: Documento de analisis de riesgos
      description: "Adjunta documentos elaborados"

  - type: checkboxes
    id: dor
    attributes:
      label: Definition of Ready
      options:        
        - label: Título claro y conciso que describe el objetivo.
        - label: Descripción completa del requerimiento.
        - label: Criterios de aceptación definidos.
        - label: Dependencias identificadas y resueltas.
        - label: Impacto analizado (funcional, técnico, seguridad).
        - label: Estimación de esfuerzo acordada por el equipo.
        - label: Prioridad asignada (Urgente, Alta, Media, Baja).
        - label: Aprobación del Product Owner registrada.
  
  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done
      options:        
        - label: Código desarrollado y revisado (Code Review aprobado).
        - label: Pruebas unitarias ejecutadas y exitosas.
        - label: Pruebas funcionales completadas (QA OK).
        - label: Documentación actualizada (README, manuales, diagramas).
        - label: Cumple criterios de aceptación sin desviaciones.
        - label: Despliegue en ambiente QA validado.
        - label: Aprobación final del Product Owner registrada.
      
  - type: textarea
    id: firmas
    attributes:
      label: Firmantes
      description: "Product Owner, Sponsor, Project Manager y Lider Tecnico"
      value: |
        | <br><br><br><br><br><br><br><br><br><br> | <br><br><br><br><br><br><br><br><br><br> |
        | Product Owner <br> Nombre <br> Cargo | Sponsor <br> Nombre <br> Cargo |
        | <br><br><br><br><br><br><br><br><br><br> | <br><br><br><br><br><br><br><br><br><br> |
        | Lider Tecnico <br> Nombre <br> Cargo | Project Manager <br> Nombre <br> Cargo | 
