name: STI-ST-918 Reporte de Bug
description: Crea un reporte de bug/error para corregir el funcionamiento del sistema
title: 'STI-ST-918-{sistema/modulo}-{titulo}'
labels: 'bug'
type: "Bug"
assignees: ["rgarcialev"]
body:
  - type: textarea
    id: descripcion-bug
    attributes:
      label: Descripcion del Bug/Error
      description: Una descripcion concisa del error encontrado.
    validations:
      required: true
  - type: textarea
    id: caso-prueba
    attributes:
      label: Caso de prueba relacionado
      description: Indica el documento de pruebas donde se encuentra el caso de uso del bug/error
      placeholder: |
        - Indica el documento aqui utilizando # <numero_issue> y el caso de uso especifico.
    validations:
      required: true
  - type: textarea
    id: pasos-reproducir
    attributes:
      label: Pasos para reproducir
      description: "Detalla los pasos para reproducir el bug."
      placeholder: |
        1. Abrir/Ir a '...'
        2. Click en '....'
        3. Ubicar '....'
        4. Ejecutar '....'
        5. Visualiza error en '....'
    validations:
      required: true
  - type: textarea
    id: comportamiento-esperado
    attributes:
      label: Resultado esperado
      description: Una descripcion concisa y clara de lo que se espera que el sistema haga.
    validations:
      required: true
  - type: textarea
    id: resultado-obtenido
    attributes:
      label: Resultado obtenido
      description: Describe lo que realmente ocurrió.
    validations:
      required: true
  - type: dropdown
    id: severidad
    attributes:
      label: Severidad
      description: Selecciona una opción
      options:
        - Crítico
        - Alto
        - Medio
        - Bajo
    validations:
      required: true
  - type: textarea
    id: ambiente
    attributes:
      label: Ambiente
      description: "Detalles sobre el contexto donde ocurrió el bug."
      placeholder: |
        - **Entorno:** DEV / TEST / Producción
        - **Navegador / Versión:**
        - **Usuario utilizado (si aplica):**
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Si aplica, agrega capturas de pantalla para ayudar a explicar el problema/error.
    validations:
      required: false

