name: STI-ST-917 Acta de aceptaci贸n para pase a producci贸n
description: Crea un acta de aceptaci贸n para realizar el pase a producci贸n de un sistema/m贸dulo
title: "Acta de Aceptaci贸n-{sistema} {modulo}"
labels: ["documentation"]
assignees: []
type: "Task"

body:

  - type: input
    id: sistema
    attributes:
      label: "Nombre del Sistema"
      placeholder: "Smartsys, Novedades, MyReporting ..."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Versi贸n / Release"
      placeholder: "Ejemplo: v1.2.3"

  - type: input
    id: fecha_aprobacion
    attributes:
      label: "Fecha de Aprobaci贸n"
      placeholder: "DD/MM/AAAA"
    validations:
      required: true

  - type: input
    id: responsable
    attributes:
      label: "Responsable del Release"
      placeholder: "Nombre y Cargo"
    validations:
      required: true

  - type: textarea
    id: objetivo
    attributes:
      label: "Objetivo"
      description: "Describe el prop贸sito del release y los cambios que se incorporar谩n en el pase a producci贸n."
      placeholder: "Ejemplo: Este release incluye correcciones cr铆ticas de seguridad y nuevas funcionalidades para el m贸dulo de autenticaci贸n."
    validations:
      required: true

  - type: checkboxes
    id: componentes
    attributes:
      label: "Componentes afectados"
      options:
        - label: Backend
        - label: Frontend
        - label: Base de datos
        - label: Infraestructura

  - type: checkboxes
    id: validaciones
    attributes:
      label: "Validaciones Previas"
      options:
        - label: Pruebas unitarias completadas
        - label: Pruebas de integraci贸n completadas
        - label: Pruebas de usuario completadas
        - label: Aprobaci贸n QA
        - label: Documentaci贸n actualizada

  - type: textarea
    id: riesgos
    attributes:
      label: "Riesgos Identificados"
      placeholder: "Ejemplo: Posible impacto en el rendimiento del login por cambios en la l贸gica de autenticaci贸n."
    validations:
      required: false

  - type: input
    id: fecha_pase
    attributes:
      label: "Fecha del Pase a Producci贸n"
      placeholder: "DD/MM/AAAA"
    validations:
      required: true

  - type: checkboxes
    id: aprobacion
    attributes:
      label: "Aprobaci贸n"
      options:
        - label: L铆der de Proyecto
        - label: QA
        - label: Product Owner

  - type: textarea
    id: notas
    attributes:
      label: " Notas Adicionales"
      placeholder: "Ejemplo: Se recomienda monitoreo intensivo durante las primeras 24 horas posteriores al despliegue."

  - type: textarea
    id: participantes
    attributes:
      label: "Participantes y Responsables"
      value: |
        | Rol                | Nombre                  | Firma |
        |--------------------|-------------------------|-------|
        | L铆der de Proyecto  |                         |       |
        | QA                 |                         |       |
        | DevOps             |                         |       |
        | Product Owner      |                         |       |
