name: STI-ST-917 Acta de aceptación para pase a producción
description: Crea un acta de aceptación para realizar el pase a producción de un sistema/módulo
title: "Acta de Aceptación-{sistema} {modulo}"
labels: ["documentation"]
assignees: []
type: "Task"
projects: "BDO-Outsourcing-S-A-C/6"

body:
  - type: markdown
    attributes:
      value: |
        # 📄 Acta de Aprobación de Release para Pase a Producción

  - type: input
    id: release_name
    attributes:
      label: "🆔 Nombre del Release"
      placeholder: "vX.Y.Z"
    validations:
      required: true

  - type: input
    id: fecha_aprobacion
    attributes:
      label: "📅 Fecha de Aprobación"
      placeholder: "DD/MM/AAAA"
    validations:
      required: true

  - type: input
    id: responsable
    attributes:
      label: "Responsable del Release"
      placeholder: "Nombre y Cargo"
    validations:
      required: true

  - type: input
    id: repositorio
    attributes:
      label: "Repositorio"
      placeholder: "URL del repositorio en GitHub"
    validations:
      required: true

  - type: dropdown
    id: branch
    attributes:
      label: "Branch"
      options:
        - main
        - release
    validations:
      required: true

  - type: textarea
    id: objetivo
    attributes:
      label: "✅ Objetivo"
      description: "Describe el propósito del release y los cambios que se incorporarán en el pase a producción."
      placeholder: "Ejemplo: Este release incluye correcciones críticas de seguridad y nuevas funcionalidades para el módulo de autenticación."
    validations:
      required: true

  - type: checkboxes
    id: componentes
    attributes:
      label: "📦 Componentes afectados"
      options:
        - label: Backend
        - label: Frontend
        - label: Base de datos
        - label: Infraestructura

  - type: textarea
    id: tickets
    attributes:
      label: "Tickets/Jiras asociados"
      placeholder: "#1234 - Ajuste en validación de usuarios"
    validations:
      required: false

  - type: checkboxes
    id: validaciones
    attributes:
      label: "🔍 Validaciones Previas"
      options:
        - label: Pruebas unitarias completadas
        - label: Pruebas de integración completadas
        - label: Pruebas de regresión completadas
        - label: Aprobación QA
        - label: Documentación actualizada

  - type: textarea
    id: riesgos
    attributes:
      label: "⚠️ Riesgos Identificados"
      placeholder: "Ejemplo: Posible impacto en el rendimiento del login por cambios en la lógica de autenticación."
    validations:
      required: false

  - type: input
    id: fecha_pase
    attributes:
      label: "📅 Fecha del Pase a Producción"
      placeholder: "DD/MM/AAAA"
    validations:
      required: true

  - type: input
    id: hora_pase
    attributes:
      label: "Hora del Pase a Producción"
      placeholder: "HH:MM (Zona horaria)"
    validations:
      required: true

  - type: textarea
    id: participantes
    attributes:
      label: "👥 Participantes y Responsables"
      placeholder: |
        | Rol                | Nombre                  | Firma |
        |--------------------|-------------------------|-------|
        | Líder de Proyecto  |                         |       |
        | QA                 |                         |       |
        | DevOps             |                         |       |
        | Product Owner      |                         |       |

  - type: checkboxes
    id: aprobacion
    attributes:
      label: "✅ Aprobación"
      options:
        - label: Líder de Proyecto
        - label: QA
        - label: DevOps
        - label: Product Owner

  - type: textarea
    id: notas
    attributes:
      label: "📚 Notas Adicionales"
      placeholder: "Ejemplo: Se recomienda monitoreo intensivo durante las primeras 24 horas posteriores al despliegue."
